### PR TITLE
go.mod concerns: v2 versioned import path, delete vendor dir

### PR DESCRIPTION
**Pull request by pda**
This PR adds `/v2` to the import path → `github.com/buildkite/bintest/v2`, as per https://blog.golang.org/v2-go-modules

Topical:
* https://donatstudios.com/Go-v2-Modules
* https://qvault.io/2020/09/15/gos-major-version-handling-sucks-from-a-fanboy/

Similar issue elsewhere:
* https://github.com/buildkite/terminal-to-html/issues/74

It also:
* deletes the `vendor/` directory
* bumps leaktest to v1.3.0

### CODE REVIEW

**Comment by pda** [comment]
I wasn't sure if I was meant to bump to `v3` for this import path change or not. I elected not to. I don't know if that'll have repercussions.

**Comment by lox** [comment]
Merge away!

**Comment by pda** [comment]
Hmm. I think this has gone horribly wrong?

```
pda@paulbookpro ~/bk/agent ❯ go get -v github.com/buildkite/bintest
go: github.com/buildkite/bintest upgrade => v2.0.0+incompatible
go: finding module for package github.com/lox/bintest/proxy
go: found github.com/lox/bintest/proxy in github.com/lox/bintest v2.0.0+incompatible
```

I suspect I should have bumped it to a new major version (v3), and it's getting confused because there exists v2.x tags with the old import path. Maybe. That's just a guess. I think I'll bump it to v3 in a new pull request.

**Comment by pda** [comment]
I pushed the [v3 thing straight to master](https://github.com/buildkite/bintest/commit/62a259d6dfe923708d2a1c8d72aaaf375e39ad7d). Looks much better now:

```
pda@paulbookpro ~/bk/agent ❯ go get -v ./...
go: finding module for package github.com/buildkite/bintest/v3
go: downloading github.com/buildkite/bintest/v3 v3.0.0
go: found github.com/buildkite/bintest/v3 in github.com/buildkite/bintest/v3 v3.0.0
github.com/buildkite/bintest/v3
github.com/buildkite/agent/v3/bootstrap/integration
```

**Pull request merged**
